name: image_list_example
description: Demonstrates how to use the image_list plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_list:
    path: ../

flutter:
  uses-material-design: true