name: image_list
description: A tappable list of images
version: 0.2.2+2
homepage: https://github.com/ricnaaru/image_list

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ric.image_list
        pluginClass: ImageListPlugin
      ios:
        pluginClass: ImageListPlugin
